services:
    api:
        build: .
        container_name: piston_api
        restart: always
        # isolate needs to create cgroups and namespaces for each submission.
        privileged: true
        ports:
            - 127.0.0.1:2000:2000
        tmpfs:
            - /tmp:exec
